// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtH3VGDMXfKVcKOMWAS3AN8tFiU6eVkQc',
    appId: '1:405166185627:web:9b66d70922964cee7d3a3e',
    messagingSenderId: '405166185627',
    projectId: 'socialhub-b45ee',
    authDomain: 'socialhub-b45ee.firebaseapp.com',
    storageBucket: 'socialhub-b45ee.firebasestorage.app',
    measurementId: 'G-X8QD1VWZH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYwmDT_-ARKr73voGcSi8b9M3PMkIYwSc',
    appId: '1:405166185627:android:0f95a982c578aa3e7d3a3e',
    messagingSenderId: '405166185627',
    projectId: 'socialhub-b45ee',
    storageBucket: 'socialhub-b45ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpRddCNaiCblIZv2XHECJogaURzXSjSJ0',
    appId: '1:405166185627:ios:ae3fdc80c26d313d7d3a3e',
    messagingSenderId: '405166185627',
    projectId: 'socialhub-b45ee',
    storageBucket: 'socialhub-b45ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSocialhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpRddCNaiCblIZv2XHECJogaURzXSjSJ0',
    appId: '1:405166185627:ios:ae3fdc80c26d313d7d3a3e',
    messagingSenderId: '405166185627',
    projectId: 'socialhub-b45ee',
    storageBucket: 'socialhub-b45ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSocialhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtH3VGDMXfKVcKOMWAS3AN8tFiU6eVkQc',
    appId: '1:405166185627:web:02355c672ccc5a057d3a3e',
    messagingSenderId: '405166185627',
    projectId: 'socialhub-b45ee',
    authDomain: 'socialhub-b45ee.firebaseapp.com',
    storageBucket: 'socialhub-b45ee.firebasestorage.app',
    measurementId: 'G-P305MMCSX6',
  );
}
